// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_AulaPerdida.Persistences;

namespace _01AulaPerdida.Migrations
{
    [DbContext(typeof(RacerContext))]
    partial class RacerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_01_AulaPerdida.Models.Atleta", b =>
                {
                    b.Property<int>("AtletaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<bool>("Profissional");

                    b.HasKey("AtletaId");

                    b.ToTable("Atleta");
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.Corrida", b =>
                {
                    b.Property<int>("CorridaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria");

                    b.Property<float>("Distancia");

                    b.Property<int>("Nome");

                    b.Property<bool>("Premiacao");

                    b.Property<int>("TrajetoId");

                    b.HasKey("CorridaId");

                    b.HasIndex("TrajetoId");

                    b.ToTable("Corridas");
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.CorridaAtleta", b =>
                {
                    b.Property<int>("AtletaId");

                    b.Property<int>("CorridaId");

                    b.HasKey("AtletaId", "CorridaId");

                    b.HasIndex("CorridaId");

                    b.ToTable("CorridaAtleta");
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.Medalha", b =>
                {
                    b.Property<int>("MedalhaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria");

                    b.Property<int?>("CorridaId");

                    b.Property<float>("Peso");

                    b.Property<int>("Quantidade");

                    b.HasKey("MedalhaId");

                    b.HasIndex("CorridaId");

                    b.ToTable("Medalha");
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.Trajeto", b =>
                {
                    b.Property<int>("TrajetoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Distancia");

                    b.Property<string>("LocalInicio");

                    b.HasKey("TrajetoId");

                    b.ToTable("Trajeto");
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.Corrida", b =>
                {
                    b.HasOne("_01_AulaPerdida.Models.Trajeto", "Trajeto")
                        .WithMany()
                        .HasForeignKey("TrajetoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.CorridaAtleta", b =>
                {
                    b.HasOne("_01_AulaPerdida.Models.Atleta", "Atleta")
                        .WithMany("CorridaAtletas")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_01_AulaPerdida.Models.Corrida", "Corrida")
                        .WithMany("CorridaAtletas")
                        .HasForeignKey("CorridaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_01_AulaPerdida.Models.Medalha", b =>
                {
                    b.HasOne("_01_AulaPerdida.Models.Corrida")
                        .WithMany("Medalhas")
                        .HasForeignKey("CorridaId");
                });
#pragma warning restore 612, 618
        }
    }
}
