// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using theRealMVC.Persistences;

namespace theRealMVC.Migrations
{
    [DbContext(typeof(banguContext))]
    partial class banguContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("theRealMVC.Models.Cela", b =>
                {
                    b.Property<int>("CelaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Area");

                    b.Property<string>("Nome");

                    b.Property<int>("QuantidadeMaxima");

                    b.HasKey("CelaId");

                    b.ToTable("Celas");
                });

            modelBuilder.Entity("theRealMVC.Models.Presidiario", b =>
                {
                    b.Property<int>("PresidiarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CelaId");

                    b.Property<string>("Nome");

                    b.Property<DateTime>("dataEntrada");

                    b.Property<DateTime>("dataSaida");

                    b.Property<int>("nivelEscolaridade");

                    b.Property<bool>("saidaTemporaria");

                    b.HasKey("PresidiarioId");

                    b.HasIndex("CelaId");

                    b.ToTable("Presidiarios");
                });

            modelBuilder.Entity("theRealMVC.Models.Presidiario", b =>
                {
                    b.HasOne("theRealMVC.Models.Cela", "Cela")
                        .WithMany("Presidiarios")
                        .HasForeignKey("CelaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
